<template>
    <!-- TODO: add suport for hover/active/focus? -->
    <div
            v-on:click="emit('click')"
            class="panelButton"
            :class="{enabled: isEnabled}">
        <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                :width="svgWidth"
                :height="svgHeight"
                :style="{marginLeft: svgMarginLeft}"
        >
            <!-- viewbox for: https://materialdesignicons.com/ -->
            <!--suppress CheckEmptyScriptTag -->
            <path v-bind:d="svgPath"/>
        </svg>
        <span v-bind:style="{marginLeft: labelMarginLeft}">
            {{label}}
        </span>
    </div>
</template>

<script>
    import util from 'util'

    export default {
        name: "PanelButton.vue",
        data: function() {
            return {
                isEnabled: true
            }
        },
        props: {
            label: String,
            svgPath: String,
            svgMarginLeft: String,
            labelMarginLeft: String,
            svgWidth: String,
            svgHeight: String,
            isEnabledByDefault: {
                type: Boolean,
                required: false,
                default: true
            }
        },
        created: function () {
            this.isEnabled = this.isEnabledByDefault
        },
        computed: {
            //TODO: make computed props and bind it to each elemnt style
            // labelStyle: function() {
            //     return {
            //         '--color': this.color,
            //         '--color-hover': this.hoverColor,
            //         '--margin-left': this.labelMarginLeft
            //     }
            // },
            // svgStyle: function () {
            //     return {
            //         '--fill': this.color,
            //         '--fill-hover': this.hoverColor,
            //         '--margin-left': this.svgMarginLeft,
            //         '--width': this.svgWidth,
            //         '--height': this.svgHeight
            //     }
            // }
        },
        methods: {
            emit(event) {
                if(!(this.isEnabled)) //supress emit if disabled
                    return

                this.$emit(event, this.label)
            },
            setState(enabled) {
                if(!(util.isBoolean(enabled)))
                    throw new TypeError(`state have to be boolean`)

                this.isEnabled = enabled
            }
        }
    }
</script>

<style scoped>
span, svg {
    position: relative;
}

.panelButton {
    position: relative;
    vertical-align: middle;
    cursor: pointer;
    top: 0.75em;
    margin-top: 0.4em;
    padding: 0.7em;
    background: rgba(0, 0, 0, 0.0);
    transition: background-color 0.3s;
}

.panelButton:hover {
    background: rgba(0, 0, 0, 0.15);
}

.panelButton * {
    display: inline-block;
    transition: color 0.2s, fill 0.15s;
    background: rgba(0, 0, 0, 0.0);
    /*color: rgba(0, 0, 0, 0.7);*/
    /*fill: rgba(0, 0, 0, 0.7);*/
    vertical-align: middle;
}

.panelButton:hover * {
    color: #3972F7;
    fill: #3972F7;
}

.panelButton:hover svg {
    animation: heartbeat 1.8s ease-in-out infinite both;
}

.pulse-more:hover svg {
    animation: heartbeat 1.4s ease-in-out infinite both;
}

/* ----------------------------------------------
* Generated by Animista on 2019-8-20 23:25:47
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation heartbeat
 * ----------------------------------------
 */
@-webkit-keyframes heartbeat {
    from {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: center center;
        transform-origin: center center;
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
    }
    10% {
        -webkit-transform: scale(0.91);
        transform: scale(0.91);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in;
    }
    17% {
        -webkit-transform: scale(0.98);
        transform: scale(0.98);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
    }
    33% {
        -webkit-transform: scale(0.87);
        transform: scale(0.87);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in;
    }
    45% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
    }
}
@keyframes heartbeat {
    from {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-transform-origin: center center;
        transform-origin: center center;
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
    }
    10% {
        -webkit-transform: scale(0.91);
        transform: scale(0.91);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in;
    }
    17% {
        -webkit-transform: scale(0.98);
        transform: scale(0.98);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
    }
    33% {
        -webkit-transform: scale(0.87);
        transform: scale(0.87);
        -webkit-animation-timing-function: ease-in;
        animation-timing-function: ease-in;
    }
    45% {
        -webkit-transform: scale(1);
        transform: scale(1);
        -webkit-animation-timing-function: ease-out;
        animation-timing-function: ease-out;
    }
}

</style>